### ISSUE TITLE
sintesis

### ISSUE THREAD

**Issue by Jaimer117** [SistemasTecTlaxiaco/sintesis-Jaimer117#2]
[Sintesis-Jaime Reyes Barrios.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-Jaimer117/files/7148334/Sintesis-Jaime.Reyes.Barrios.pdf)

**Comment by Edwin-1012** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
